// Copyright 2023 Google LLC
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file or at
// https://developers.google.com/open-source/licenses/bsd

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: capability.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next_id = 16
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED         Capability = 0
	Capability_CAPABILITY_SAFE                Capability = 1
	Capability_CAPABILITY_FILES               Capability = 2
	Capability_CAPABILITY_NETWORK             Capability = 3
	Capability_CAPABILITY_RUNTIME             Capability = 4
	Capability_CAPABILITY_READ_SYSTEM_STATE   Capability = 5
	Capability_CAPABILITY_MODIFY_SYSTEM_STATE Capability = 6
	Capability_CAPABILITY_OPERATING_SYSTEM    Capability = 7
	Capability_CAPABILITY_SYSTEM_CALLS        Capability = 8
	Capability_CAPABILITY_ARBITRARY_EXECUTION Capability = 9
	Capability_CAPABILITY_CGO                 Capability = 10
	Capability_CAPABILITY_UNANALYZED          Capability = 11
	Capability_CAPABILITY_UNSAFE_POINTER      Capability = 12
	Capability_CAPABILITY_REFLECT             Capability = 13
	Capability_CAPABILITY_EXEC                Capability = 14
	Capability_CAPABILITY_READ_ENVIRONMENT    Capability = 15
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0:  "CAPABILITY_UNSPECIFIED",
		1:  "CAPABILITY_SAFE",
		2:  "CAPABILITY_FILES",
		3:  "CAPABILITY_NETWORK",
		4:  "CAPABILITY_RUNTIME",
		5:  "CAPABILITY_READ_SYSTEM_STATE",
		6:  "CAPABILITY_MODIFY_SYSTEM_STATE",
		7:  "CAPABILITY_OPERATING_SYSTEM",
		8:  "CAPABILITY_SYSTEM_CALLS",
		9:  "CAPABILITY_ARBITRARY_EXECUTION",
		10: "CAPABILITY_CGO",
		11: "CAPABILITY_UNANALYZED",
		12: "CAPABILITY_UNSAFE_POINTER",
		13: "CAPABILITY_REFLECT",
		14: "CAPABILITY_EXEC",
		15: "CAPABILITY_READ_ENVIRONMENT",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":         0,
		"CAPABILITY_SAFE":                1,
		"CAPABILITY_FILES":               2,
		"CAPABILITY_NETWORK":             3,
		"CAPABILITY_RUNTIME":             4,
		"CAPABILITY_READ_SYSTEM_STATE":   5,
		"CAPABILITY_MODIFY_SYSTEM_STATE": 6,
		"CAPABILITY_OPERATING_SYSTEM":    7,
		"CAPABILITY_SYSTEM_CALLS":        8,
		"CAPABILITY_ARBITRARY_EXECUTION": 9,
		"CAPABILITY_CGO":                 10,
		"CAPABILITY_UNANALYZED":          11,
		"CAPABILITY_UNSAFE_POINTER":      12,
		"CAPABILITY_REFLECT":             13,
		"CAPABILITY_EXEC":                14,
		"CAPABILITY_READ_ENVIRONMENT":    15,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_capability_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_capability_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Capability) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Capability(num)
	return nil
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{0}
}

// Next_id = 3
type CapabilityType int32

const (
	CapabilityType_CAPABILITY_TYPE_UNSPECIFIED CapabilityType = 0
	CapabilityType_CAPABILITY_TYPE_DIRECT      CapabilityType = 1
	CapabilityType_CAPABILITY_TYPE_TRANSITIVE  CapabilityType = 2
)

// Enum value maps for CapabilityType.
var (
	CapabilityType_name = map[int32]string{
		0: "CAPABILITY_TYPE_UNSPECIFIED",
		1: "CAPABILITY_TYPE_DIRECT",
		2: "CAPABILITY_TYPE_TRANSITIVE",
	}
	CapabilityType_value = map[string]int32{
		"CAPABILITY_TYPE_UNSPECIFIED": 0,
		"CAPABILITY_TYPE_DIRECT":      1,
		"CAPABILITY_TYPE_TRANSITIVE":  2,
	}
)

func (x CapabilityType) Enum() *CapabilityType {
	p := new(CapabilityType)
	*p = x
	return p
}

func (x CapabilityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityType) Descriptor() protoreflect.EnumDescriptor {
	return file_capability_proto_enumTypes[1].Descriptor()
}

func (CapabilityType) Type() protoreflect.EnumType {
	return &file_capability_proto_enumTypes[1]
}

func (x CapabilityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CapabilityType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CapabilityType(num)
	return nil
}

// Deprecated: Use CapabilityType.Descriptor instead.
func (CapabilityType) EnumDescriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{1}
}

type CapabilityInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the package.
	PackageName *string `protobuf:"bytes,1,opt,name=package_name,json=packageName" json:"package_name,omitempty"`
	// Name associated with this capability.
	Capability *Capability `protobuf:"varint,2,opt,name=capability,enum=capslock.proto.Capability" json:"capability,omitempty"`
	// The dependency path to where the capability is incurred.
	DepPath *string `protobuf:"bytes,3,opt,name=dep_path,json=depPath" json:"dep_path,omitempty"`
	// The dependency path to where the capability is incurred.
	// Each element is a single function or method.
	Path []*Function `protobuf:"bytes,6,rep,name=path" json:"path,omitempty"`
	// The location of the package.
	PackageDir *string `protobuf:"bytes,4,opt,name=package_dir,json=packageDir" json:"package_dir,omitempty"`
	// Classification of how the capability was incurred.
	CapabilityType *CapabilityType `protobuf:"varint,5,opt,name=capability_type,json=capabilityType,enum=capslock.proto.CapabilityType" json:"capability_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CapabilityInfo) Reset() {
	*x = CapabilityInfo{}
	mi := &file_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityInfo) ProtoMessage() {}

func (x *CapabilityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityInfo.ProtoReflect.Descriptor instead.
func (*CapabilityInfo) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{0}
}

func (x *CapabilityInfo) GetPackageName() string {
	if x != nil && x.PackageName != nil {
		return *x.PackageName
	}
	return ""
}

func (x *CapabilityInfo) GetCapability() Capability {
	if x != nil && x.Capability != nil {
		return *x.Capability
	}
	return Capability_CAPABILITY_UNSPECIFIED
}

func (x *CapabilityInfo) GetDepPath() string {
	if x != nil && x.DepPath != nil {
		return *x.DepPath
	}
	return ""
}

func (x *CapabilityInfo) GetPath() []*Function {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *CapabilityInfo) GetPackageDir() string {
	if x != nil && x.PackageDir != nil {
		return *x.PackageDir
	}
	return ""
}

func (x *CapabilityInfo) GetCapabilityType() CapabilityType {
	if x != nil && x.CapabilityType != nil {
		return *x.CapabilityType
	}
	return CapabilityType_CAPABILITY_TYPE_UNSPECIFIED
}

type Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Site          *Function_Site         `protobuf:"bytes,2,opt,name=site" json:"site,omitempty"`
	Package       *string                `protobuf:"bytes,3,opt,name=package" json:"package,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{1}
}

func (x *Function) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Function) GetSite() *Function_Site {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *Function) GetPackage() string {
	if x != nil && x.Package != nil {
		return *x.Package
	}
	return ""
}

type ModuleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Version       *string                `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleInfo) Reset() {
	*x = ModuleInfo{}
	mi := &file_capability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleInfo) ProtoMessage() {}

func (x *ModuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleInfo.ProtoReflect.Descriptor instead.
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleInfo) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *ModuleInfo) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

type PackageInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  *string                `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	// ignored_files contains a list of source files in the package directory
	// that were ignored due to the build configuration and build tags.  See
	// https://pkg.go.dev/golang.org/x/tools/go/packages#Package.IgnoredFiles
	// for more information.
	IgnoredFiles  []string `protobuf:"bytes,2,rep,name=ignored_files,json=ignoredFiles" json:"ignored_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	mi := &file_capability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{3}
}

func (x *PackageInfo) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *PackageInfo) GetIgnoredFiles() []string {
	if x != nil {
		return x.IgnoredFiles
	}
	return nil
}

type EnvVarInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepPath       *string                `protobuf:"bytes,1,opt,name=dep_path,json=depPath" json:"dep_path,omitempty"`
	VarName       *string                `protobuf:"bytes,2,opt,name=var_name,json=varName" json:"var_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVarInfo) Reset() {
	*x = EnvVarInfo{}
	mi := &file_capability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVarInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVarInfo) ProtoMessage() {}

func (x *EnvVarInfo) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVarInfo.ProtoReflect.Descriptor instead.
func (*EnvVarInfo) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{4}
}

func (x *EnvVarInfo) GetDepPath() string {
	if x != nil && x.DepPath != nil {
		return *x.DepPath
	}
	return ""
}

func (x *EnvVarInfo) GetVarName() string {
	if x != nil && x.VarName != nil {
		return *x.VarName
	}
	return ""
}

type CapabilityInfoList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of CapabilityInfo protos.
	CapabilityInfo []*CapabilityInfo `protobuf:"bytes,1,rep,name=capability_info,json=capabilityInfo" json:"capability_info,omitempty"`
	ModuleInfo     []*ModuleInfo     `protobuf:"bytes,2,rep,name=module_info,json=moduleInfo" json:"module_info,omitempty"`
	PackageInfo    []*PackageInfo    `protobuf:"bytes,3,rep,name=package_info,json=packageInfo" json:"package_info,omitempty"`
	EnvVarInfo     []*EnvVarInfo     `protobuf:"bytes,4,rep,name=env_var_info,json=envVarInfo" json:"env_var_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CapabilityInfoList) Reset() {
	*x = CapabilityInfoList{}
	mi := &file_capability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityInfoList) ProtoMessage() {}

func (x *CapabilityInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityInfoList.ProtoReflect.Descriptor instead.
func (*CapabilityInfoList) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilityInfoList) GetCapabilityInfo() []*CapabilityInfo {
	if x != nil {
		return x.CapabilityInfo
	}
	return nil
}

func (x *CapabilityInfoList) GetModuleInfo() []*ModuleInfo {
	if x != nil {
		return x.ModuleInfo
	}
	return nil
}

func (x *CapabilityInfoList) GetPackageInfo() []*PackageInfo {
	if x != nil {
		return x.PackageInfo
	}
	return nil
}

func (x *CapabilityInfoList) GetEnvVarInfo() []*EnvVarInfo {
	if x != nil {
		return x.EnvVarInfo
	}
	return nil
}

type CapabilityCountList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of capability counts.
	CapabilityCounts map[string]int64 `protobuf:"bytes,1,rep,name=capability_counts,json=capabilityCounts" json:"capability_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ModuleInfo       []*ModuleInfo    `protobuf:"bytes,2,rep,name=module_info,json=moduleInfo" json:"module_info,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapabilityCountList) Reset() {
	*x = CapabilityCountList{}
	mi := &file_capability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityCountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityCountList) ProtoMessage() {}

func (x *CapabilityCountList) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityCountList.ProtoReflect.Descriptor instead.
func (*CapabilityCountList) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{6}
}

func (x *CapabilityCountList) GetCapabilityCounts() map[string]int64 {
	if x != nil {
		return x.CapabilityCounts
	}
	return nil
}

func (x *CapabilityCountList) GetModuleInfo() []*ModuleInfo {
	if x != nil {
		return x.ModuleInfo
	}
	return nil
}

type CapabilityStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Capability      *Capability            `protobuf:"varint,1,opt,name=capability,enum=capslock.proto.Capability" json:"capability,omitempty"`
	Description     *string                `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	DirectCount     *int64                 `protobuf:"varint,3,opt,name=direct_count,json=directCount" json:"direct_count,omitempty"`
	TransitiveCount *int64                 `protobuf:"varint,4,opt,name=transitive_count,json=transitiveCount" json:"transitive_count,omitempty"`
	ExampleCallpath []*Function            `protobuf:"bytes,5,rep,name=example_callpath,json=exampleCallpath" json:"example_callpath,omitempty"`
	Count           *int64                 `protobuf:"varint,6,opt,name=count" json:"count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilityStats) Reset() {
	*x = CapabilityStats{}
	mi := &file_capability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityStats) ProtoMessage() {}

func (x *CapabilityStats) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityStats.ProtoReflect.Descriptor instead.
func (*CapabilityStats) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{7}
}

func (x *CapabilityStats) GetCapability() Capability {
	if x != nil && x.Capability != nil {
		return *x.Capability
	}
	return Capability_CAPABILITY_UNSPECIFIED
}

func (x *CapabilityStats) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CapabilityStats) GetDirectCount() int64 {
	if x != nil && x.DirectCount != nil {
		return *x.DirectCount
	}
	return 0
}

func (x *CapabilityStats) GetTransitiveCount() int64 {
	if x != nil && x.TransitiveCount != nil {
		return *x.TransitiveCount
	}
	return 0
}

func (x *CapabilityStats) GetExampleCallpath() []*Function {
	if x != nil {
		return x.ExampleCallpath
	}
	return nil
}

func (x *CapabilityStats) GetCount() int64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type CapabilityStatList struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CapabilityStats []*CapabilityStats     `protobuf:"bytes,1,rep,name=capability_stats,json=capabilityStats" json:"capability_stats,omitempty"`
	ModuleInfo      []*ModuleInfo          `protobuf:"bytes,2,rep,name=module_info,json=moduleInfo" json:"module_info,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilityStatList) Reset() {
	*x = CapabilityStatList{}
	mi := &file_capability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityStatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityStatList) ProtoMessage() {}

func (x *CapabilityStatList) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityStatList.ProtoReflect.Descriptor instead.
func (*CapabilityStatList) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{8}
}

func (x *CapabilityStatList) GetCapabilityStats() []*CapabilityStats {
	if x != nil {
		return x.CapabilityStats
	}
	return nil
}

func (x *CapabilityStatList) GetModuleInfo() []*ModuleInfo {
	if x != nil {
		return x.ModuleInfo
	}
	return nil
}

type Function_Site struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      *string                `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	Line          *int64                 `protobuf:"varint,2,opt,name=line" json:"line,omitempty"`
	Column        *int64                 `protobuf:"varint,3,opt,name=column" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Function_Site) Reset() {
	*x = Function_Site{}
	mi := &file_capability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function_Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function_Site) ProtoMessage() {}

func (x *Function_Site) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function_Site.ProtoReflect.Descriptor instead.
func (*Function_Site) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Function_Site) GetFilename() string {
	if x != nil && x.Filename != nil {
		return *x.Filename
	}
	return ""
}

func (x *Function_Site) GetLine() int64 {
	if x != nil && x.Line != nil {
		return *x.Line
	}
	return 0
}

func (x *Function_Site) GetColumn() int64 {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return 0
}

var File_capability_proto protoreflect.FileDescriptor

const file_capability_proto_rawDesc = "" +
	"\n" +
	"\x10capability.proto\x12\x0ecapslock.proto\"\xa2\x02\n" +
	"\x0eCapabilityInfo\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12:\n" +
	"\n" +
	"capability\x18\x02 \x01(\x0e2\x1a.capslock.proto.CapabilityR\n" +
	"capability\x12\x19\n" +
	"\bdep_path\x18\x03 \x01(\tR\adepPath\x12,\n" +
	"\x04path\x18\x06 \x03(\v2\x18.capslock.proto.FunctionR\x04path\x12\x1f\n" +
	"\vpackage_dir\x18\x04 \x01(\tR\n" +
	"packageDir\x12G\n" +
	"\x0fcapability_type\x18\x05 \x01(\x0e2\x1e.capslock.proto.CapabilityTypeR\x0ecapabilityType\"\xbb\x01\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x04site\x18\x02 \x01(\v2\x1d.capslock.proto.Function.SiteR\x04site\x12\x18\n" +
	"\apackage\x18\x03 \x01(\tR\apackage\x1aN\n" +
	"\x04Site\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x03R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x03R\x06column\":\n" +
	"\n" +
	"ModuleInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"F\n" +
	"\vPackageInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rignored_files\x18\x02 \x03(\tR\fignoredFiles\"B\n" +
	"\n" +
	"EnvVarInfo\x12\x19\n" +
	"\bdep_path\x18\x01 \x01(\tR\adepPath\x12\x19\n" +
	"\bvar_name\x18\x02 \x01(\tR\avarName\"\x98\x02\n" +
	"\x12CapabilityInfoList\x12G\n" +
	"\x0fcapability_info\x18\x01 \x03(\v2\x1e.capslock.proto.CapabilityInfoR\x0ecapabilityInfo\x12;\n" +
	"\vmodule_info\x18\x02 \x03(\v2\x1a.capslock.proto.ModuleInfoR\n" +
	"moduleInfo\x12>\n" +
	"\fpackage_info\x18\x03 \x03(\v2\x1b.capslock.proto.PackageInfoR\vpackageInfo\x12<\n" +
	"\fenv_var_info\x18\x04 \x03(\v2\x1a.capslock.proto.EnvVarInfoR\n" +
	"envVarInfo\"\xff\x01\n" +
	"\x13CapabilityCountList\x12f\n" +
	"\x11capability_counts\x18\x01 \x03(\v29.capslock.proto.CapabilityCountList.CapabilityCountsEntryR\x10capabilityCounts\x12;\n" +
	"\vmodule_info\x18\x02 \x03(\v2\x1a.capslock.proto.ModuleInfoR\n" +
	"moduleInfo\x1aC\n" +
	"\x15CapabilityCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x98\x02\n" +
	"\x0fCapabilityStats\x12:\n" +
	"\n" +
	"capability\x18\x01 \x01(\x0e2\x1a.capslock.proto.CapabilityR\n" +
	"capability\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fdirect_count\x18\x03 \x01(\x03R\vdirectCount\x12)\n" +
	"\x10transitive_count\x18\x04 \x01(\x03R\x0ftransitiveCount\x12C\n" +
	"\x10example_callpath\x18\x05 \x03(\v2\x18.capslock.proto.FunctionR\x0fexampleCallpath\x12\x14\n" +
	"\x05count\x18\x06 \x01(\x03R\x05count\"\x9d\x01\n" +
	"\x12CapabilityStatList\x12J\n" +
	"\x10capability_stats\x18\x01 \x03(\v2\x1f.capslock.proto.CapabilityStatsR\x0fcapabilityStats\x12;\n" +
	"\vmodule_info\x18\x02 \x03(\v2\x1a.capslock.proto.ModuleInfoR\n" +
	"moduleInfo*\xc7\x03\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCAPABILITY_SAFE\x10\x01\x12\x14\n" +
	"\x10CAPABILITY_FILES\x10\x02\x12\x16\n" +
	"\x12CAPABILITY_NETWORK\x10\x03\x12\x16\n" +
	"\x12CAPABILITY_RUNTIME\x10\x04\x12 \n" +
	"\x1cCAPABILITY_READ_SYSTEM_STATE\x10\x05\x12\"\n" +
	"\x1eCAPABILITY_MODIFY_SYSTEM_STATE\x10\x06\x12\x1f\n" +
	"\x1bCAPABILITY_OPERATING_SYSTEM\x10\a\x12\x1b\n" +
	"\x17CAPABILITY_SYSTEM_CALLS\x10\b\x12\"\n" +
	"\x1eCAPABILITY_ARBITRARY_EXECUTION\x10\t\x12\x12\n" +
	"\x0eCAPABILITY_CGO\x10\n" +
	"\x12\x19\n" +
	"\x15CAPABILITY_UNANALYZED\x10\v\x12\x1d\n" +
	"\x19CAPABILITY_UNSAFE_POINTER\x10\f\x12\x16\n" +
	"\x12CAPABILITY_REFLECT\x10\r\x12\x13\n" +
	"\x0fCAPABILITY_EXEC\x10\x0e\x12\x1f\n" +
	"\x1bCAPABILITY_READ_ENVIRONMENT\x10\x0f*m\n" +
	"\x0eCapabilityType\x12\x1f\n" +
	"\x1bCAPABILITY_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CAPABILITY_TYPE_DIRECT\x10\x01\x12\x1e\n" +
	"\x1aCAPABILITY_TYPE_TRANSITIVE\x10\x02B\"Z github.com/google/capslock/proto"

var (
	file_capability_proto_rawDescOnce sync.Once
	file_capability_proto_rawDescData []byte
)

func file_capability_proto_rawDescGZIP() []byte {
	file_capability_proto_rawDescOnce.Do(func() {
		file_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capability_proto_rawDesc), len(file_capability_proto_rawDesc)))
	})
	return file_capability_proto_rawDescData
}

var file_capability_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_capability_proto_goTypes = []any{
	(Capability)(0),             // 0: capslock.proto.Capability
	(CapabilityType)(0),         // 1: capslock.proto.CapabilityType
	(*CapabilityInfo)(nil),      // 2: capslock.proto.CapabilityInfo
	(*Function)(nil),            // 3: capslock.proto.Function
	(*ModuleInfo)(nil),          // 4: capslock.proto.ModuleInfo
	(*PackageInfo)(nil),         // 5: capslock.proto.PackageInfo
	(*EnvVarInfo)(nil),          // 6: capslock.proto.EnvVarInfo
	(*CapabilityInfoList)(nil),  // 7: capslock.proto.CapabilityInfoList
	(*CapabilityCountList)(nil), // 8: capslock.proto.CapabilityCountList
	(*CapabilityStats)(nil),     // 9: capslock.proto.CapabilityStats
	(*CapabilityStatList)(nil),  // 10: capslock.proto.CapabilityStatList
	(*Function_Site)(nil),       // 11: capslock.proto.Function.Site
	nil,                         // 12: capslock.proto.CapabilityCountList.CapabilityCountsEntry
}
var file_capability_proto_depIdxs = []int32{
	0,  // 0: capslock.proto.CapabilityInfo.capability:type_name -> capslock.proto.Capability
	3,  // 1: capslock.proto.CapabilityInfo.path:type_name -> capslock.proto.Function
	1,  // 2: capslock.proto.CapabilityInfo.capability_type:type_name -> capslock.proto.CapabilityType
	11, // 3: capslock.proto.Function.site:type_name -> capslock.proto.Function.Site
	2,  // 4: capslock.proto.CapabilityInfoList.capability_info:type_name -> capslock.proto.CapabilityInfo
	4,  // 5: capslock.proto.CapabilityInfoList.module_info:type_name -> capslock.proto.ModuleInfo
	5,  // 6: capslock.proto.CapabilityInfoList.package_info:type_name -> capslock.proto.PackageInfo
	6,  // 7: capslock.proto.CapabilityInfoList.env_var_info:type_name -> capslock.proto.EnvVarInfo
	12, // 8: capslock.proto.CapabilityCountList.capability_counts:type_name -> capslock.proto.CapabilityCountList.CapabilityCountsEntry
	4,  // 9: capslock.proto.CapabilityCountList.module_info:type_name -> capslock.proto.ModuleInfo
	0,  // 10: capslock.proto.CapabilityStats.capability:type_name -> capslock.proto.Capability
	3,  // 11: capslock.proto.CapabilityStats.example_callpath:type_name -> capslock.proto.Function
	9,  // 12: capslock.proto.CapabilityStatList.capability_stats:type_name -> capslock.proto.CapabilityStats
	4,  // 13: capslock.proto.CapabilityStatList.module_info:type_name -> capslock.proto.ModuleInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_capability_proto_init() }
func file_capability_proto_init() {
	if File_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capability_proto_rawDesc), len(file_capability_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_capability_proto_goTypes,
		DependencyIndexes: file_capability_proto_depIdxs,
		EnumInfos:         file_capability_proto_enumTypes,
		MessageInfos:      file_capability_proto_msgTypes,
	}.Build()
	File_capability_proto = out.File
	file_capability_proto_goTypes = nil
	file_capability_proto_depIdxs = nil
}
